version: '3'

services:

  ## MySQL
  mysql:
    image: mysql:8.0.35
    container_name: java-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kottom2
      - MYSQL_DATABASE=user
    ports:
      - 3036:3036

  app:
    build: ./
    container_name: java-app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/user
    depends_on:
      - mysql